name: flaskhello CI

on:
    push:
        branches-ignore:
            - main
        paths:
            - 'flaskhello/**'
            - '.github/workflows/ci-flaskhello.yml'
    pull_request:
        paths:
            - 'flaskhello/**'
            - '.github/workflows/ci-flaskhello.yml'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: pip install -r flaskhello/requirements.txt

            - name: Run tests
              run: pytest flaskhello/tests/
